version: '3.3'
services:
  postgres:
    image: postgres:12.5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tweetboard
    volumes:
      - my-db:/var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - 5432:5432
  app:
    build: .
    env_file: .env
    environment:
      DB_HOST: db
    volumes:
      - ./source:/usr/app/source
    ports:
      - "5000:5000"
    command:
      [
        "../scripts/wait-for-it.sh",
        "db:5432",
        "--",
        "uvicorn",
        "app.main:app",
        "--port",
        "5000"
      ]
# Names our volume
volumes:
  my-db:
